### ISSUE TITLE
Doesn't work on GNOME 3.32

### ISSUE THREAD

**Issue by drakkar1969** [dsboger/gnome-shell-extension-bumblebee-status#2]
Fails with
```
TypeError: _bumblebeeIndicator is undefined
TypeError: this._construct is not a function
```

**Comment by dsboger-zz** [comment]
Thanks for reporting! I've pushed a new release that should fix this. It is still pending review in extensions.gnome.org, but you can install manually by cloning this repo and following the instructions in the README.

Could you test it and see if it works? Thanks again!

**Comment by drakkar1969** [comment]
Thanks for the super-quick fix!
Tested on Arch Linux by updating the AUR git package and now working again.

And thanks for your work on this extension, super useful (and the only one that really seems to work for bumblebee status)
